package:
  name: remixt
  version: '0.4.1'

source:
  git_url: https://dranew@bitbucket.org/dranew/remixt.git
  git_rev: v0.4.1

requirements:
  build:
    - python
    - cython
    - numpy
    - boost_source ==1.60.0

  run:
    - python
    - numpy
    - scipy
    - pandas >=0.17.1
    - pypeliner >=0.4.1
    - statsmodels
    - scikit-learn
    - pyyaml

about:
  home: http://bitbucket.org/dranew/remixt
  summary: 'ReMixT is a tool for joint inference of clone specific segment and breakpoint copy number in whole genome sequencing data'

